### ISSUE TITLE
how specify the reducer where apply ActionCreators.undo()

### ISSUE THREAD

**Issue by brasycad** [omnidan/redux-undo#143]
If you have several reducers like this:

```js
export const rootReducer = combineReducers<IAppState>({
    appLayout: appLayoutReducers,
    searcherData: searcherReducers,
    appModel: appModelReducers,
    georef: undoable(georefReducers, { limit: 5, undoType: 'UNDO_GEOREF', redoType: 'REDO_GEOREF' }),
    works: undoable(worksReducers, { limit: 2, undoType: 'UNDO_WORKS', redoType: 'REDO_WORKS' }),
    docsProvider: docsReducers
});
```

if I dispatch ActionCreators.undo() how I can specify whats the reducer I want to undo?

Thanks in advance

**Comment by omnidan** [comment]
@brasycad if you dispatch `ActionCreators.undo()` without setting `undoType`, it will trigger all `undoable` reducers. If you specify your own `undoType`, you need to dispatch the specified type to trigger the reducer.

In your example, you can trigger an undo for `georef` by dispatching `UNDO_GEOREF`. The same applies to `works` and `UNDO_WORKS`.

BTW: This issue is similar to #142 - if you have any further questions, feel free to reopen :smile:

**Comment by bfang711** [comment]
so by dispatching `UNDO_GEOREF`, do you mean do `dispatch(ActionCreators.undo('UNDO_GEOREF'))` or simply do `dispatch({type:'UNDO_GEOREF'})`?

**Comment by omnidan** [comment]
@bfang711 the type property has to be `UNDO_GEOREF`, so: `dispatch({type:'UNDO_GEOREF'})`.

The `ActionCreators.undo` function creates an action with a special `type` property which is the default value for `undoType`.
