### ISSUE TITLE
Present management

### ISSUE THREAD

**Issue by ugo-buonadonna** [omnidan/redux-undo#154]
Hello!

I'm using this library on top of a big Redux store.

According to the way the `.present` field is currently handled in the library, making a reducer undoable causes  a break of the access to the fields in the store everywhere that particular data is used outside the reducer (Redux sagas, selectors... ).

This because you have to add `.present` to access current data.

It would be very nice to have a configuration of the way the 'present' state is managed, to avoid breaking access to the particular data field.

For example, allowing this:
--------------------
**FROM THIS**

> {
>   past: [{value: 1}, {value:2}],
>   present: {value: 3},
>   future: [{value: 4}, {value:5}]
> }

**TO THIS**

> {
>   value: 3,
>   past: [{value: 1}, {value:2}],
>   future: [{value: 4}, {value:5}]
> }

This would avoid breaking code that access the current value outside the reducer, that in a big project means to change dozens lines of code.

Thank you

**Comment by davidroeca** [comment]
Hi @ugo-buonadonna,

While in theory this would provide for simpler code changes, it also has the potential to lead to a lot of weird bugs, namely a collision in name space. If your reducer references past and future keys, you'll have to conventionally know to rename them or remove them--in fact there's another _latestUnfiltered key that the library uses and there are no guarantees that there won't be more keys used by the library in the future.

Until we prioritize working on finding a clever work-around to modify every function to handle a polluted state object given the caveats above, I'd recommend abstracting your selectors by referencing a top-level function relied upon by all the others. Using [reselect](https://github.com/reactjs/reselect) it would look something like this:

```js
import { createSelector } from 'reselect'
// merely change this to/from state => state.myReducer.present
const getMyState = state => state.myReducer 
const getMyStateX = createSelector(
  [ getMyState ],
  (myState) => myState.x
)
```

[Redux Form's](http://redux-form.com/6.6.0/docs/api/FormValueSelector.md) `formValueSelector` implements this with  `getFormState`, and similar libraries should be able to support something similar.

**Comment by ugo-buonadonna** [comment]
Hmm i see you point, but in a project there are situations where you can't just modify the store and change all references to it. 
For example, in a team of 3-4 people working on a project made of 15-20 components, if there are components that references other component's store to handle some common logic (not using selector, i.e. Redux Saga `select`), you can imagine that modifying the store of that component would result in a big, expensive refactor. 
This is not an ideal situation, but can happen for some complex UI interactions.

That being said, you solution is probably the cleanest, but as i pointed out, not always feasible.

That's why i made two fork out of your library, one to extend the preexisting object structure , and another to extend a preexisting Immutable structure, setting `present` and `future` through `Map`.

Thanks!

**Comment by TimMurnaghan** [comment]
@ugo-buonadonna Did you put your fork anywhere accessible?
That means I obviously agree with you. I want something composable - so that I can drop in redo without writing an access layer.
Of course, @davidroeca is right as well. This is caused by the difficulty in accessing things "out-of-band" in reducers. Logically we want the undo data separate but if we end up putting it in the same Immutable object we can't help but fall victim to naming issues. The problem being that the solution chosen here isn't composable. Actually a naming convention would be preferable. If I was told that it's not safe to have any top level keys starting with "_" that would be OK by me. 

Either that or not putting it in the Immutable data at all. I'd also be fine with this being data inside the reducer. That would have huge benefits in not polluting the data it is managing, but it would make the reducer stateful which would be against some people's religion. The trade off between being pure and being well encapsulated and composable is not always well understood - and in this case purity would take a second place in my, quite large, app.

**Comment by davidroeca** [comment]
@TimMurnaghan the whole point behind selectors is that they enable any state structure to be composable. If your undoable state is relied upon by higher-order reducers, you can compose the selectors to reflect that structure. 

Here's the fork you're looking for https://github.com/ugo-buonadonna/redux-undo

I'm still not entirely convinced that this is a positive addition to the library but hopefully it can solve these problems in the interim.

**Comment by TimMurnaghan** [comment]
@davidroeca Thanks for the link. In the end I did a simpler version of my own just inside the app - with the wrapped data under it's own magically named key - which is fine as I own the naming structure of the other keys.

On the wider point , the "but selectors" argument which always comes up in this context is not quite enough. If you have any access at all outside the selectors than you're exposed to the fact that the wrapping changes the structure. I haven't seen anybody who actually writes all their code like that. Selectors tend to be used more sparingly so they're not an encapsulating abstraction layer.

So while you're right that I can compose selectors it doesn't answer my problem because I don't have selectors everywhere. That means that adding the wrapper IS a breaking change and the lack of composability of the reducer wrapper is an interesting question to debate.

**Comment by omnidan** [comment]
I do not think this is a good idea as it hurts composability of higher order reducers, as well as introducing many potential bugs with name collisions. While this library will not support such a feature, you may use a fork that does this if you prefer. (Be careful when using it in combination with other higher order reducers and make sure you do not produce key collisions!)
