### ISSUE TITLE
Replace instead of inserting

### ISSUE THREAD

**Issue by nanandn** [omnidan/redux-undo#155]
Is there a way to replace the last edit instead of inserting a new entry in the history?
I am using redux-undo in a wizard like UI. I want to store the edits at the end of each step in the wizard, so I can go back to the previous step. 'insert' is copying things into _lastUnfiltered, but undo restores the last state from the history. So if I have some unfiltered actions between two inserts, the state is not saved in the history as I expected. 

Is there a way to force a replace (what is in _lastUnfiltered)?

**Comment by davidroeca** [comment]
Hi @nanandn,

Filtering an action essentially means that redux-undo will not track a change in the undo history. An undo will go back to the last item in the past, and _latestUnfiltered will become the first item in the future since it was the last present tracked by redux-undo. 

So if you're filtering a lot, you'll have to make sure that you've fired an unfiltered action prior to undoing, or else everything you've filtered will have been... filtered.

Say your wizard has 3 steps and you've filtered every action other than the actions STEP_FORWARD and I_WILL_UNDO.

undoable present:

#### Working on step 1
**past length: 0**
* Filter every action prior to STEP_FORWARD.
* You're ready to move on, so you STEP_FORWARD (__make sure this updates state or it will be filtered implicitly__--this is an optimization that prevents redux-undo from crashing if you're firing a lot of superfluous actions, though it could be improved)
#### Working on step 2
**past length: 1**
* Filter every action prior to STEP_FORWARD, or I_WILL_UNDO
* If you want to undo to step 1, you'd have to first implicitly dispatch a I_WILL_UNDO (__make sure this updates state__) and then call undo. This will provide you a future with the I_WILL_UNDO state. You will undo to the state in step 1 prior to the STEP_FORWARD.
* You're ready to move on, so you call STEP_FORWARD (__make sure this updates state__)
#### Working on step 3
**past length: 2**
* Filter every action prior to STEP_FORWARD, or I_WILL_UNDO
* If you want to undo to step 2, you'd have to first implicitly dispatch a I_WILL_UNDO (__make sure this updates state__) and then call undo. This will provide you a future with the I_WILL_UNDO state. You would have undone to the state in step prior to stepping forward.
* You're done

**Comment by davidroeca** [comment]
Now that https://github.com/omnidan/redux-undo/pull/161 has been merged, you also have the option of specifying a function that groups actions together similar to the way you've requested. Instead of filtering, you can provide actions of the form `{'type': 'MY_TYPE', 'group': 'SECTION_1'}`, and a `groupBy` function like:

```js
const groupBy = (action) => action.group
const undoable_reducer = undoable(reducer, { 'groupBy': groupBy})
```

Subsequent actions that yield the same `groupBy` return value will be grouped into a single step. You could also have a more complex `groupBy` logic depending on how you define the function. See https://github.com/omnidan/redux-undo#grouping-actions for more

**Comment by davidroeca** [comment]
Closing for now. Please reopen if there are issues with this sort of implementation
