### ISSUE TITLE
treating multiple "identical" actions as one undo step

### ISSUE THREAD

**Issue by jcdufourd** [omnidan/redux-undo#158]
This is a follow up of #115 and #139.

Here is the context I am working with: there are actions that happen in series, and the whole series should create one undo. Example of action series are: onChange on a text field (happens for every character typed) and changing a object position by dragging. 

I implemented a filter which remembers the last action, compares the last action and the current action, and if action type and action parameters match (only the values change), the filter returns false so that no new undo state is created. I was counting on the fact that even if an action is filtered, the current state is updated. At the end of a series, the current state would contain the last value (of the text field or of the position). The first action of the series pushes to history the state before the action series, and the first action not in the series pushes to history the state after the series, with the last value. 

#139, with the use of _latestUnfiltered, defeats my naive strategy. The _latestUnfiltered contains the state after the first action of the series, the latest action that was not filtered. Pushing _latestUnfiltered to history instead of the current state replaces the current state at the end of the series with the state after the first action of the series. 

I do not understand the need for #139, but at least in my case, it is counter-productive and maybe should be put behind a config switch ?

Note: I have (almost?) resolved my situation with a dirty hack: in my filter, I detect the existence of a _latestUnfiltered and I set it to the current state. I tried deleting _latestUnfiltered but everything fails then.

**Comment by davidroeca** [comment]
A PR would be very welcome. Fortunately the library is considered beta so moving the latestUnfiltered/your implementation as config options may be possible, though not ideal. I'd argue that if you find yourself hacking filters with impure functions (you're storing state in your filter), that this is a sign that either your code or the library itself may benefit from design changes--we could potentially store this alongside past, present, future, and _latestUnfiltered.

The point of #139 is that you don't always have control over which actions get fired, especially if you're working with external libraries. Truly filtering actions is valuable in this case. Imagine you have a thunk action creator that then dispatches sub actions. You would want to undo the thunk action creator and filter every sub-action. Here, the strategy is to watch for "boundary" actions (e.g. actions the user has taken, that you care about, rather than downstream actions). 

Your problem seems to be the flip side of this--you want to filter out actions the user has taken and infer the boundary (e.g. the change in action type). One alternative could be to watch for a user's contextual changes, with blurs and mouseUps instead of squashing changes and drags. I'm sure there are other ways to handle this, like handling every fifteenth or hundredth of these changes. Ideally with the state stored in redux. Here, you're explicitly defining the boundary between similar user actions.

Alternatively, maybe a config parameter 'squasher' might be more accurate than 'filter', where there could be saved 'squash' state in redux on which you can perform this specific logic.

**Comment by jcperez-ch** [comment]
I do agree with @jcdufourd.  In the other hand I understand the motivation of the `_latestUnfiltered` state.

Still, I am trying to filter only `pushState` history events, so I can work with snapshots of the past.  This `_latestUnfiltered` works as another past in the use case of this application.

A boolean configuration where `_latestUnfiltered` is disabled would be great, even when I understand it is not ideal.  The requirements specify that going one step to the past should take the latest snapshot of that past, and not precisely the initial one.

**Comment by davidroeca** [comment]
Do you both truly mean to "filter" actions or do something different? It seems to me as though there is room for a completely separate feature that can be implemented for these different use cases. IIUC it almost sounds as though both of you would like a grouping feature rather than filtering, since filtering in these cases feels like a hack

**Comment by jcperez-ch** [comment]
Filter is for me:
To generate a history entry only when the `filter` configuration functions returns true.
At the end, whatever gets pushed to the `past` array is the `_lastUnfiltered` which is an snapshot of the present state when the latest `past` entry got inserted.

so, the present state can still be modified by a bunch of actions that doesn't affect the `filter` configuration (aka it returns `false` when they get dispatched).  But when I insert a new entry in the past we want to insert the latest `present` not the `_lastUnfiltered`.

So probably the misunderstanding is what actually the `filter` function means, so.  As far as I understand your context, yeah, we can define a `chunkBy` or `groupBy` function instead of filter, to implement what we want.

**Comment by davidroeca** [comment]
Yep, this is what I was thinking--config setup like this:

```js
{
// ...define filters and whatever else...
    groupAction: (action, currentState, previousHistory) => {
        // jcdufourd's use case
        return action.type
    }
}
```
And then in the reducer, subsequent actions classified in the same group will be treated as a single step in undo/redo. The reducer could check if the next group is the same as the current group, and will update both present and _latestUnfiltered with no changes to past. By default the grouping will be null, and the null case will be the current functionality of the library.

**Comment by jcdufourd** [comment]
Thank you both for all that discussion.
I agree that the word 'filter' is overloaded. What I wanted to do was to insert change in the process, and the existing filter process was the (only) one allowing a change.
I totally get the need for #139-style filtering now. I am glad you understand the need for my style of filtering.

I like the 'squasher' idea. If you want the squasher to be pure and have no memory (not even in a closure), then you need to remember the previous action and pass it to the squash function.
`{
        squasher: (currentAction, previousAction, currentState, previousHistory) => {
                // application specific comparison between actions
                return shouldSquash;
        }
}`
It would be clear when _latestUnfiltered is useful (=with a 'filter') and when it should be ignored (=with a 'squasher').
In the documentation, it would be clear that changes related to a filtered action will be ignored, and changed related to squashed actions will be 'accumulated'.

Maybe we should even pass an array of past actions to the squasher to cover all possible cases, but that may be overkill. 
`{
        squasher: (currentAction, pastActions, currentState, previousHistory) => {
                // application specific comparison between actions
                return shouldSquash;
        }
}`

I will not be able to work on this this week, but I may be able to propose a PR next week if you agree.

**Comment by jcperez-ch** [comment]
So, @davidroeca any idea on how the `filter` function and the `squash` function will work together?  I believe they are mutually exclusive, and also, which would have priority over which? I have plans to work on it today if we can finally decide.

**Comment by jcdufourd** [comment]
Indeed, filter and squash seem mutually exclusive, and we should check that only one of the two is present in the config.

**Comment by davidroeca** [comment]
So I'm thinking filter is a way of completely ignoring anything in the
undo/redo history so that comes first, then things get grouped. groupBy is
probably a more accurate name, since some extra state will be stored. I
actually took a crack at this last night but it remains untested and may
not cover everything--feel free to check it out
https://github.com/davidroeca/redux-undo/commit/661ebd006ff73482f43fa5916d3c3144da34a8d4

**Comment by jcperez-ch** [comment]
Ok @davidroeca I was thinking in a completely different approach.  Some kind of action that synchronizes the `_latestUnfiltered` with the present.

Like here: https://github.com/jcperez-ch/redux-undo/commit/1dd75776c90a001eb051aa922cf7d1eea00f90ac

**Comment by davidroeca** [comment]
Hm so in this case, the unwrapped reducer's state would have to take care
of the squash state, no? Or it would require a closure like before.

The idea behind my approach is you can group something with a number or
string, and redux-undo will take care of the rest. Maybe even pass a meta
prop to your action that contains how it will be grouped

**Comment by jcperez-ch** [comment]
Yeah, with the squash approach we allow the users when to perform an squash, no matter if they are filtering or not, I guess we are trying to solve different use cases

**Comment by jcperez-ch** [comment]
Any inputs @jcdufourd I think you wanted to pass a `previousAction` but not sure if my approach would be enough to solve your use case.

Beware that squash function has the type of:
```js
(action: Action, state: State, history: StateWithHistory<State>) => boolean
```

Just as the filter action.

**Comment by davidroeca** [comment]
Interesting. I'm not sure we're solving for different use cases. 

Here, groupBy has the following signature:
```js
groupBy: (action: Action, state: State, history: StateWithHistory<State>) => ?Number // or could be string
```

Spec:
* If filter occurs, its state change is ignored by redux-undo's history, as that is what a filter does.
* If the current action is in the same group as the previous action (and the current group is not null), update present and _latestUnfiltered to the latest and don't update the past/future.
* If current action is in a different group or null, insert normally.

So I think we're trying to handle the same use case, just different approaches

**Comment by jcperez-ch** [comment]
@davidroeca yes. I already created OR 160, I felt like defending my approach.  But I would like to hear from the community which of the two `groupBy` or `quash` should go.

Also you can take a look at the unit tests that I created, so community can digest easily what the squash function does.

**Comment by davidroeca** [comment]
I believe the initial request in this issue was resolved by https://github.com/omnidan/redux-undo/pull/161

I know that as mentioned by @jcperez-ch in https://github.com/omnidan/redux-undo/pull/160 there may be benefits to changing the filtering behavior, so please start/manage that discussion in a new issue/pull request. Closing for now--please reopen if groupBy implementation issues surface
