### ISSUE TITLE
Add note in readme that auto-applied distinct state filter does a shallow equality check

### ISSUE THREAD

**Issue by tnrich** [omnidan/redux-undo#189]
Hey there,

I just ran into an issue where it looked like nothing was changing with my "presentState" but I was still getting additional states added.

![untitled](https://user-images.githubusercontent.com/2730609/32115658-453d04ea-bb0d-11e7-9eb6-b4c85be15f1f.gif)

I solved it by adding my own filter that did a deep equality check, but it took me a while to figure out what was going wrong. Is there any chance you could add a note to the readme about this?

Thanks!

**Comment by xargi** [comment]
Although if you are following the principles of redux properly, you should not be mutating any part of the state object tree in-place and you should not need a deep equality comparison then.

**Comment by tnrich** [comment]
@xargi so you're saying this would have been solved had I not been mutating anything in place within the reducer? I am not totally sure that would be the case. I think just returning a new object from a reducer would cause the shallow equality not to work. But that is not against redux principles I don't believe. For example: 

```
function myReducer (state, action) {
  return {}
}
```
if the above `myReducer` were one of the sub-reducers below the undoable reducer, the shallow equality check would break. 

I know it's a contrived example but I believe that might be what's happening in my case.

**Comment by xargi** [comment]
You can avoid breaking shallow equality by returning the same state object if nothing changes. Anyway, the only thing the redux docs really emphasize about it is that when you change something you should return a new identity from the reducer instead of mutating the state object.

Adding the deep comparison to the distinct state filter would be more of a bandage than a solution, as you will run into the same issue elsewhere if your state behaves like that.
