### ISSUE TITLE
not work with multiple redux store

### ISSUE THREAD

**Issue by qingtong234** [omnidan/redux-undo#191]
my project is allitter diffrent from other's. my project have two redux-stores, because the second store is maintained in npm package, when it changes, the main redux will subscribe the changed parts. 

when i use this awesome undo-package, it can only listen to my main store's action, so how can i both listen the two store's?

I'am looking forward for your answers

**Comment by omnidan** [comment]
@qingtong234 you can use `undoable` on each of your redux stores. however, they will not be synchronized unless you add special logic for that.

**Comment by nmay231** [comment]
This problem seems out of scope for most use-cases of `redux-undo` to implement an interface for multiple redux stores.

However as @omnidan said, you can write a custom middleware function that would share actions between both stores. You can read up about writing Redux middlewares [here](https://redux.js.org/advanced/middleware).
