### ISSUE TITLE
How can i Undo or Redo a batch of actions at the same time ?

### ISSUE THREAD

**Issue by TheNightElf** [omnidan/redux-undo#202]
```js
undoable: undoable(undoReducer, {
    filter: function includeAction() {
        return action.type.match('$$')
    }
})
```

**Comment by omnidan** [comment]
I do not think this is possible right now. Maybe with custom groupBy and filter functions. Would you be interested on working on a PR (either documenting how to do it with current mechanisms, or developing a new mechanism for this feature)?

**Comment by gaopinghuang0** [comment]
This is my way using custom groupBy. I also created a PR #216 with more details.

For example, an `onClick` event handler may dispatch a batch of actions. My way is to surround the batch of actions with `start()` and `end()`. 
```js
import { batchGroupBy } from './batchGroupBy'

const mapDispatchToProps = (dispatch, ownProps) => ({
  onClick: (evt) => {
    batchGroupBy.start()

    dispatch(action1)
    dispatch(action2)
    dispatch(action3)
    
    batchGroupBy.end()
  }
});
```
The basic idea is that once `batch.start()`, all the subsequent actions will return the same group value until meet `batch.end()`. Then `redux-undo` will automatically save them in one group, without inserting a new state in the `past` array.

```js
// batchGroupBy.js

import { groupByActionTypes } from 'redux-undo'

export const batchGroupBy = {
  _group: null,
  start(group = cuid()) {
    this._group = group
  },
  end() {
    this._group = null
  },
  init(rawActions) {
    const defaultGroupBy = groupByActionTypes(rawActions)
    return (action) => this._group || defaultGroupBy(action)
  }
};
```
We can config the reducer like this:
```js
import { batchGroupBy } from './batchGroupBy'

const rootReducer = combineReducers({
  ui: uiReducer,
  document: undoable(documentReducer, {
    groupBy: batchGroupBy.init([SOME_ACTION])
  }),
});
```

**Comment by gaopinghuang0** [comment]
I think I found a simpler solution by using a small package: [redux-batched-actions](https://github.com/tshelburne/redux-batched-actions). It has `batchActions()` that converts a batch of actions into a single action, which will be handled by a high-order reducer automatically. Therefore, a batch of actions will just insert one new state into the history, and undo/redo needs no extra effort.

This has an extra benefit: all actions in the batch are reduced at once, and the UI needs to re-render once. Otherwise, if each action is dispatched synchronously, it may potentially cause a lot of re-rendering and the state may be wrong in between those dispatches.

**Comment by Arkellys** [comment]
Is this code still supposed to work? I get an error when I try to use it:

`Cannot set property '_group' of undefined`

```
  19 | 	this._group = group;
  20 | },
  21 | end() {
> 22 | 	this._group = null;
  23 | },
  24 | init(rawActions) {
  25 | 	const defaultGroupBy = groupByActionTypes(rawActions);
```

**Comment by Arkellys** [comment]
My bad, the code works. The problem was just that I forgot to use an arrow function so it messed up with `this`.
