### ISSUE TITLE
Should clearHistory also null out _latestUnfiltered?

### ISSUE THREAD

**Issue by srvance** [omnidan/redux-undo#226]
I have an app where users can stop and start different sessions throughout the lifetime of the app. I'm finding that initiating a second session has undo history even though I dispatched `clearHistory()` at the close of the previous session. It seems that `_latestUnfiltered` still has the value from the previous session and gets pushed into `past` when the second session starts.

Am I doing something wrong or is this really the bug I think it may be?

**Comment by srvance** [comment]
I ended up getting around this by clearing the history after fully initializing the new session so that `_latestUnfiltered` represents the initial state of the new session rather than the residual state of the old. It seems though that this may be a workaround rather than the correct behavior.

**Comment by TimSusa** [comment]
@srvance IMO you are right! It seems to me, that _latestUnfiltered holds up the whole store all the time, which is suboptimal for performance (especially in my case). There does not seem to be any possibility to clear _latestUnfiltered out, which is a very bad showstopper for me, to be honest.

**Comment by nmay231** [comment]
This is the intended behavior even if it is not what you are looking for. What is happening is that you leave the ending state of the first session stored in `_latestUnfiltered` (*and* `present`). Then this gets pushed into `past` when you initialize the second session.

To achieve what you need (without changing values manually), you can init the state at the beginning of the next user session and *then* clear history while still preserving the init state.

If you are worried about memory usage, you can clear before and after sessions.

@TimSusa `_latestUnfiltered` is necessary to keep track of states if you are filtering certain actions from history. It is basically a temporary variable between filtered actions.
```js
// This action was filtered, so present cannot be pushed into past right away
_latestUnfiltered = present
present = newState
// With the next unfiltered action...
past = [...past, _latestUnfiltered] // We can now add it
```

While it does add overhead, it is required to keep the expected behavior with filtered actions
