### ISSUE TITLE
Using diff/patch for storing/restoring states?

### ISSUE THREAD

**Issue by cdax** [omnidan/redux-undo#36]
For applications with massive state trees and minimal state changes, it might be a better idea to store previous or future versions of the state as diffs, and then restoring them using a patch algorithm. I'm willing to work on this if others think this might be a good idea.

**Comment by omnidan** [comment]
@cdax One thing you can do to optimize performance is only wrap a part of your state tree with `undoable`. If you only make many small parts undoable, it won't take as much of a performance hit.

You are right, using diffs between states would be super interesting, maybe it should be an external module, though. If you would be willing to help with this, that'd be really appreciated :smile:

**Comment by MoLow** [comment]
this could be very very useful!

**Comment by arekkas** [comment]
Any news on this?

**Comment by omnidan** [comment]
@arekkas unfortunately not, but a PR for this would be very welcome :grin:

**Comment by yariza** [comment]
Here's a PR! #145

**Comment by cormacrelf** [comment]
If part of your state tree doesn't change, that part has reference equality (a === b) with the same part of the previous state. Reference equality between objects in JavaScript means that two objects point to the exact same piece of memory, as they are essentially just fancy pointers. If they drop off the end of your undo count limit they will be GC'd, but until then, they are referred to by redux-undo's 'past' array.

Here's an example, where A changes and therefore so does Root, but B does not change. Even if B is huge, we actually reuse the memory from state 1 in state 2, so we incur no cost for storing it 'twice'.

```javascript
reducer(state = { A: 1, B: { /* some huge object */ } }, action) {
  return { A: state.A + 1, B: state.B };
}
```

```
past state:
* Root
  * A
  * B
present state:
* Root'
  * A'
  * B
```

Yes, if you're immutably modifying a list using list.slice(0).filter(x => x > 10) or something like that, the new list itself will take up a bit of memory, but given the use case of really huge data, assume that `A` is a huge object with many sub-objects, one of which is changed. The memory occupied by A's own structure is negligible compared to the size of all of its children, and in fact probably negligible compared to a computed diff. If you use Immutable.js for your state tree, you can more easily preserve reference equality than using plain Object.assign/Array.slice/..., but _even plain objects will have this property_.

It's kind of pointless trying to use diffs, because storing the diff is likely more memory-intensive than simply storing the individual states themselves: diffs are new objects with data that describes how to apply them, while storing the states doesn't need this metadata. And diffs are somewhat expensive to compute, and it is difficult to ensure they are correct especially if someone is using non-plain-JS objects.

I would argue, then, that if you have problems storing states efficiently in the usage pattern described, it's not something to solve with redux-undo, but instead a problem to solve with other tools like Immutable.js and its efficient trie-based structural sharing.

**Comment by whmountains** [comment]
I think storing actions with checkpoints would be more efficient.

**Comment by davidroeca** [comment]
@whmountains `groupby` achieves this by categorizing actions into groups and storing changes to present when the group changes. See the readme for more details

**Comment by whmountains** [comment]
@davidroeca That's useful, thanks!

I was actually talking about something more like what redux devtools uses.

**Comment by JannicBeck** [comment]
I have faced a similar problem:

Storing massive state trees pushes the limits of this library, especially if your persist your store inside a storage engine like localStorage.

* Your localStorage will be full very fast.
* When you rehydrate you can no longer benefit from reference equality as explained by @cormacrelf 

If you've your states are bigger than your actions on average and you persist them, you might be better off with storing actions.

Hence I wrote [undox](https://github.com/JannicBeck/undox), a library for storing actions instead of states

**Comment by nmay231** [comment]
This is definitely an interesting idea, but has already been solved by other libraries like [Redux Undo Stack](https://github.com/stephan83/redux-undo-stack) or even approached from a different angle like undox (see the previous comment).

Additionally, @cormacrelf 's [comment above](https://github.com/omnidan/redux-undo/issues/36#issuecomment-276567591) goes into great detail why this might not even be necessary at all.

And as discussed in the PR #145, there might be a performance tradeoff.

Closing :+1:
