### ISSUE TITLE
initialState on store is not preserved

### ISSUE THREAD

**Issue by tiemevanveen** [omnidan/redux-undo#49]
`InitialState` set on the `store` is not preserved when using `redux-undo`. 
So just to be clear, I mean the initialState on the store, not on a reducer.

Code to configure my store:

    import { createStore } from 'redux';
    import reducer from '../reducers/index';

    const initialStoreState = { foo: 'bar' };
    const store = createStore(reducer, initialStoreState);

Reducer code:
    
    // index.js 
    combineReducers({
        foo: undoable(foo)
    })

    // foo.js
    function foo(state = {}, action) {
        return state;
    }

Container: 

    function mapStateToProps(state) {
        return state.foo
    }

state in `mapStateToProps` will be `{}` instead of `{ foo: 'bar' }`

**Comment by tiemevanveen** [comment]
(Discussing a fix with @pl12133 on Gitter)

**Comment by pl12133** [comment]
It looks like responding to the action `{ type: '@@redux/INIT' }` was re-initializing the reducer to it's `initialState`, so this bug can be fixed by returning `state` if the action is `@@redux/INIT`.

The preliminary fix for this bug is available at https://github.com/pl12133/redux-undo/tree/fix-init and will be merged after proper testing.

**Comment by pl12133** [comment]
Thanks to @tiemevanveen for the detailed write up on this bug!

**Comment by tiemevanveen** [comment]
Great, thanks for the quick fix! \0/

**Comment by tiemevanveen** [comment]
PR: https://github.com/omnidan/redux-undo/issues/50

**Comment by omnidan** [comment]
@tiemevanveen I think this can be closed now, right?

**Comment by tiemevanveen** [comment]
yeah, thanks!
