### ISSUE TITLE
document history API

### ISSUE THREAD

**Issue by FredyC** [omnidan/redux-undo#7]
Have you thinking about including something like that? For example it might be helpful to know that there is something in history and enable the buttons in UI. Or even to display list of actions in the history.

I am just wondering how it would fit with Redux topology since this is just function hooked on reducers. One way could be to use Symbol to write these information onto the state object and then offer the API that would read these symbols.

**Comment by omnidan** [comment]
Actually, you can already access the history, it's just not documented (right now).

It's as simple as doing `.history` instead of `.currentState`, which contains:

 * `past` (an array of past values)
 * `present` (almost always the same as `currentState`)
 * `future` (an array of future values, for when you did undo and want to redo)

I hope this helps you :) Feel free to contribute to the README.md and write a section about this. I'll rename this issue accordingly

**Comment by FredyC** [comment]
Oh, I seriously had to look into this how does it work. No promise, but I will try to write docs. Thanks for info!

**Comment by omnidan** [comment]
No problem :grin:

**Comment by omnidan** [comment]
Done in https://github.com/omnidan/redux-undo/commit/a9a3259a7a7d3892f6cf80a3d994129b0a5a23fd

I haven't gotten time to work on the other issues yet (life has been keeping me busy :unamused:), but I set myself a deadline on Friday :grin:
