### ISSUE TITLE
How to work with multiple reducers?

### ISSUE THREAD

**Issue by kattehjem** [omnidan/redux-undo#77]
When I make multiple reducers undoable and then call `store.dispatch(ActionCreators.undo())`, the states of all those reducers will be set to the previous value at once. Is there a way to only undo the last state change?

For example, if one reducer sets state.a and the other sets state.b, and I call action 1 that sets state.a to 'Frank', and then I call action 2 that sets state.b to 'Claire', I want `store.dispatch(ActionCreators.undo())` to only revert state.b to the previous value, but not state.a (which should only be affected by an additional undo step). Is this possible?

**Comment by omnidan** [comment]
@kattehjem In that case, you'll have to group all the reducers that you want to fire together in an object, like this:

```js
{
  fireAtOnce: undoable({
    reducerA: ...,
    reducerB: ...
  }),
  reducerC: ...
}
```

Alternatively you could set separate `undo` actions for separate reducers to control them independently.

**Comment by kattehjem** [comment]
I don't think I understand it. If I change my code to something like this, I'll get `Uncaught TypeError: reducer is not a function.`

```
const rootReducer = combineReducers({
    firstReducer,
    secondReducers,
    undoGroup: undoable({
        thirdReducer,
        fourthReducer
    })
}
```

**Comment by omnidan** [comment]
@kattehjem sorry, my bad (it's late :sweat_smile:), you need to use `combineReducers` again, like this:

```js
const rootReducer = combineReducers({
    firstReducer,
    secondReducers,
    undoGroup: undoable(combineReducers({
        thirdReducer,
        fourthReducer
    }))
}
```

I also edited my other post to reflect that.

**Comment by kattehjem** [comment]
Great, that works. Thanks a lot!

**Comment by omnidan** [comment]
You're welcome :grin:

**Comment by norbiu** [comment]
Is there a different way to do this? Our project is pretty big now, so regrouping reducers at this point would require a great deal of refactoring.

**Comment by omnidan** [comment]
@norbiu unfortunately, I don't think so. What specifically is problematic for you when using this approach?

**Comment by norbiu** [comment]
@omnidan We want to use this for our pdf editor. We have a reducer for our in page elements that keeps track of position, size, color etc and another reducer for the pages of the document that tracks page selects and adding / removing pages. 

We also have other reducers that we might need (not sure, I don't have access to my work files at the moment). But we also have 5 or 6 other reducers that we will certainly not need. The problem is that they're all part of the root reducer. They're all second level, never felt the need to group them further until now.

Another solution would be to make our root reducer undoable and then only include the handful of actions we need. Would that be feasible? Would it make the application slow over time? Would I have to ... limit the limit of undos if I include all of my reducers?

**Comment by omnidan** [comment]
@norbiu if you wrap all your reducers with `undoable` without specifying a special action type via the second `options` arguments, they will always trigger at the same time if you dispatch an `undo` action from `redux-undo` `ActionTypes`. Then you don't need to nest your reducers into another object. You still need to select your states via `state.reducerName.present`, however.

**Comment by norbiu** [comment]
@omnidan I'm not trying to wrap all my reducers individually with undoable, just the root reducer, which includes all of my reducers, even ones that I don't need.

I want to be able to undo redo using keyboard shortcuts, so I would need everything to work using the default action type `UNDO`.

Would you recommend all of the reducers being part of undoable even though the state is affected by only a few actions?

**Comment by davidroeca** [comment]
@norbiu I'd recommend that--just [use a filter](https://github.com/omnidan/redux-undo/blob/master/README.md#filtering-actions) to include the actions that handle user input

**Comment by danschumann** [comment]
Hmmm..  I just ran into this situation as well.  I had undoable implemented simply, but hadnt tested, so I also would have a bunch of code to refactor, and I don't really want to change the structure..

```
combineReducerts({
frames: undoable require('./frames')
points: undoable require('./points')
})
```

And the problem is, I call undo, and it does undoes both, instead of only 1.

IE.  Create a new project.  Change frames around, change points around, call undo.  You would expect it to only undo the points, but it does both.

Hmm. I realize the problem is probably my structure and I should change it... hmmm.  If the snapshots were timestamped, I could probably do some hacks for the undo/redo events, and ignore unless the current undoable was the relevant timestamp.  

Or, has there been some sort of global fix?  Perhaps a global queue reference?  Or some pipeline add-on I can use?  IE, assign a pipeline to `undoable` upon initialization, and then every time something is pushed, it updates the pipeline, and during undo/redo, it checks the pipeline.  That way, multiple different `undoable` reducers can talk.

**Comment by danschumann** [comment]
Ahh, I've got it! 

I already have a custom reducer to apply `befores` and `afters` reducers ( I have some post-processing stuff, which is independent of data and can be recomputed at any time -- this isn't an anti-pattern when dealing with highly nested structures ).

```

combined = combineReducers({
  frames: undoable require('./frames'), {undoType: "FRAMES::UNDO"}
  points: undoable require('./points'), {undoType: "POINTS::UNDO"} # do same for redo
})

undoEvents=[]
redoEvents=[]
module.exports = (state, action) =>

  _.map befores, (reducer, n) =>
    state = reducer(state, action)

  combinedState = combined(state, action)

# here I'll have to see if points, frames, or both changed
  if combinedState.points isnt state.points and combinedState.frames isnt state.frames
    undoEvents.push("BOTH_CHANGED")
  else if combinedState.points isnt state.points
     undoEvents.push("POINTS_CHANGED")
  else if combinedState.frames isnt state.frames
      undoEvents.push("FRAMES_CHANGED")

  if combinedState isnt state
    state = _.extend {}, state, combinedState
  _.map afters, (reducer, n) =>
    state = reducer(state, action)

  state

$(window).on 'keycode', (e) ->
  if e.keyCode is UNDO_KEY
     switch undoEvent = undoEvents.pop()
         when "BOTH_CHANGED"
            dispatch "FRAMES:"UNDO"
            dispatch "POINTS::UNDO"
         when "FRAMES_CHANGED"
              dispatch "FRAMES::UNDO"
         when "POINTS_CHANGED"
              dispatch "POINTS::UNDO"
     redoEvents.push undoEvent
```
or something like that!

Yea, I'll try that.  (note I just wrote this on github, probably bugs)


On second though, rather than `BOTH_CHANGED`, I'll probably end up pushing `undoEvents.push([  FRAMES_UNDO, POINTS_UNDO ])`

Or.. it'll look like 
```
possibleUndo = []
if combinedState.points isnt state.points
  possibleUndo.push POINTS_UNDO
if combinedState.frames isnt state.frames
  possibleUndo.push FRAMES_UNDO
# other reducers possibly pushing UNDOs
if possibleUndo.length
  undoEvents.push possibleUndo
```
So that I can add as man different reducers as I need.

This way, undoables don't need to be from the same `undoable` instance.  It would fix the other guy's problem.

**Comment by danschumann** [comment]
Aight, so it works.  Here's a gist

https://gist.github.com/danschumann/bf209508f896ac2c8c53a658ef920c53

I can run `undo()`, and it'll be respectful of both instances of `undoable`.

Yea, it adds a little overhead to every reducer, and yea, it's one more thing to manage.  It is possible though.

**Comment by danschumann** [comment]
Here's a gist to copy the new structure to the old structure on the fly.
This is the fix the guy was asking for.
It's a hack yea, but it doesn't add much overhead.
https://gist.github.com/danschumann/ea15f86cdeed5df6c363df97e3c82e20

**Comment by danschumann** [comment]
Disregard any comments you got via email.  it took me longer to write this comment than to update my codebase to have the non-hacked structure!
