### ISSUE TITLE
use symbols for history

### ISSUE THREAD

**Issue by omnidan** [omnidan/redux-undo#8]
> When you set something as undoable, the structure of the state changes and you need to reflect it somewhere else in the code. This should be changed with Symbols.

**Comment by FredyC** [comment]
There could be also weak check if Symbol is actually available and use some weird looking property name instead like `__undoState`. Either way it would require some API to access the data in there. Something like this.

```
import { getHistory } from 'redux-undo';

function select(state) {
  return {
    visibleTodos: selectTodos(state.todos, state.visibilityFilter),
    visibilityFilter: state.visibilityFilter,
    undoDisabled: getHistory(state.todos).past.length === 0, // disable undo button when undo is not possible (past not available)
    redoDisabled: getHistory(state.todos).future.length === 0 // disable redo button when redo is not possible (future not available)
  };
}
```

**Comment by omnidan** [comment]
@FredyC thanks for the suggestion of checking if `Symbol` is available, I'll definitely do that. I started working on this in the train (so I didn't get very far :stuck_out_tongue: ) and right now I have `history(state.todos)` implemented already (it uses symbols too).

**Comment by FredyC** [comment]
@omnidan Great to hear that! I've just run into small bug which is basically in the area you are changing, so might fix it as well. Thing is that you are not returning the `history` object in the state when using `filter`. As the result the first action (that pass through filter) is not undoable. I think it's caused because this way you skip INIT action from redux.

**Comment by omnidan** [comment]
@FredyC the [filtering actions](https://github.com/omnidan/redux-undo#filtering-actions) section should explain why you are running into this issue:

> Note that the helpers always accept @@redux/INIT too in order to store your initial state. If you don't want this, define your own filter function.

**Comment by FredyC** [comment]
Ok, I've missed that, but I am sure that I wouldn't be the first one. Perhaps there could be at least some development warning otherwise it behaves really oddly and it's hard to find the culprit.

**Comment by omnidan** [comment]
@FredyC development warning? what do you mean? If you filter out actions and you make a whitelist and don't include `INIT`, that's the developers problem. By default it just accepts all actions (including `INIT`) and the helpers include init too. I'll think about #11 - but this is really something that could be done with a custom filter function or maybe a new helper?

**Comment by omnidan** [comment]
Also what should we do about `.currentState`? should using that still be possible, or should it just be deprecated as a breaking change? :stuck_out_tongue:

**Comment by FredyC** [comment]
Well at the current point I think it's still possible to create breaking changes, it almost seems that I am first one trying to use your lib ;)

**Comment by omnidan** [comment]
@FredyC Yeah I was thinking about just making a new version :sweat_smile:

**Comment by FredyC** [comment]
Regarding the development warning ... It's just that it took me like an hour to realize that I need to include my init action into the filter :) I think that #11 would solve that nicely, because the init action would be always considered till you need something else.

**Comment by gaearon** [comment]
Can you expand on what you propose? I'm a bit confused. Do you want to put Symbols *inside* the user-generated object? That doesn't seem right to me, as it's a mutation. What's so bad about `currentState` or `present`?

**Comment by omnidan** [comment]
@gaearon I don't mind `currentState` either, but I can see where he's coming from - just being able to add `undoable` to your reducers and keep the rest of the code the same would be nice.

What I would do is make the `history` (which already exists) a symbol and then put the user generated object on the same level with history `{ ...reducerResult, [HISTORY_SYMBOL]: updatedHistory }` instead of `{ currentState: reducerResult, history: updatedHistory }`

**Comment by omnidan** [comment]
@FredyC I agree on your comment about #11 - it would be nicer to have the helpers just deal with the actions they were passed and not `INIT` too.

**Comment by FredyC** [comment]
@gaearon: It's not really mutation because with the Symbol cannot really conflict nor override any user data in there. It's completely hidden. I've already used Symbols in my [LiLL](https://github.com/BlackDice/Lill) library to ease on memory footstep.

**Comment by gaearon** [comment]
1. If the user `Object.freeze`s their state, you wouldn't be able to put a symbol on it.
2. I'm not sure “hidden” is good. How would persistence and restoration of user session work?

**Comment by omnidan** [comment]
ad 1: true

ad 2: you're right, maybe we should just keep it in `.currentState`, it's a lot less magic than `history(state)` - and all you have to do is change a small thing, it's a tradeoff, but `.currentState` is the cleaner solution

**Comment by FredyC** [comment]
@gaearon Well are there really people who would use `freeze`? I haven't seen it as a very often practice much yet. In overall it causes more problems than it helps.

Do you really need persistence of undo history? Like serialization?

**Comment by gaearon** [comment]
>Well are there really people who would use freeze? I haven't seen it as a very often practice much yet. In overall it causes more problems than it helps.

It being unpopular now (in may ways due to outdated benchmarks) is not a reason to make it impossible to use it with this library. Redux doesn't make assumptions about state; I don't think Redux Undo should either.

>Do you really need persistence of undo history? Like serialization?

Yes. It's a valid part of the state. If there's a bug report, or a test scenario, or a developer session, I want to see all the state. **In many apps using undo/redo it's a core feature: e.g. Photoshop history.** It's really a first class concept and not something you should hide as an implementation detail of a library.

**Comment by omnidan** [comment]
> In many apps using undo/redo it's a core feature: e.g. Photoshop history. It's really a first class concept and not something you should hide as an implementation detail of a library.

:+1: if you're using `redux-undo`, you're probably accessing its history too (at least to check if buttons should be enabled/disabled)

**Comment by omnidan** [comment]
I think this can be closed now. If you guys have any more comments feel free to post them here, I'll still read them :)

**Comment by gaearon** [comment]
I'd probably rename `currentState` to `present` though. Less typing and more specific. What do you think?

**Comment by omnidan** [comment]
@gaearon I've thought about that too, I think I'll do just that in the next release (which will have the new filter too :smile:) - working on it!

**Comment by FredyC** [comment]
Yeah I guess I'll have to make a fork and do it just for me, because it really bugs me. I don't agree, but I don't want to argue any more.

**Comment by FredyC** [comment]
One more thing, if you have undo redo like core feature I am almost sure that people would implement by themselves. I have seen this library more like a quick solution or a recipe.

**Comment by omnidan** [comment]
@FredyC that's alright. you could also simply write a wrapper around `redux-undo`. I don't think that's a good solution, but it would solve your problem :stuck_out_tongue:

It still is a quick solution, adding `.present` really isn't that much to ask for, is it? :wink:

**Comment by gaearon** [comment]
One of the reasons I'm pushing for this is because explicitness and predictability are key benefits of Redux. Wherever possible I'd rather keep them.

Another reason I'm pushing for this is that we don't need to reinvent the wheel. [elm-undo-redo](https://github.com/TheSeamau5/elm-undo-redo) works the same way, and its use of [Elm Architecture](https://github.com/evancz/elm-architecture-tutorial/) is explicit. I think Redux extensions like this should also embrace Elm Architecture explicitly.

**Comment by FredyC** [comment]
Well my main problem with `.currentState` (w/e) is that you can easily miss the spot where to change it and suddenly you are getting weird stuff in your app - the history object. This is especially bothersome if you don't have actual unit-tests so something may come up later.

Also imagine if there would be more libs that would go the same way. Suddenly you may end up with `state.currentState.present.mystate.whatever` and it will be totally crazy!

**Comment by gaearon** [comment]
>Well my main problem with .currentState (w/e) is that you can easily miss the spot where to change it and suddenly you are getting weird stuff in your app - the history object.

Fair. In Elm's case, type system saves you from this, but it doesn't in ours. Still, it's pretty much like any state refactoring: you have to be conscious about it. I think having DevTools and/or logger also should help diagnose the issue. In my view this is still preferable to implicitness.

>Also imagine if there would be more libs that would go the same way. Suddenly you may end up with state.currentState.present.mystate.whatever and it will be totally crazy!

Actually I think it's good because the order is important. If all of them try to put Symbols on top of user's state, you'll end up with inconsistent state. For example, no matter how ridiculous this use case is, it should be possible to apply `undoable` twice and have an undo list governed by another undo list. While you wouldn't do it in an app, this being possible shows that the idea is consistent. When each library puts a Symbol on the state, you can't tell which one is managing which one.

**Comment by omnidan** [comment]
> Well my main problem with .currentState (w/e) is that you can easily miss the spot where to change it and suddenly you are getting weird stuff in your app - the history object.

I understand that problem and I would love to prevent that, but Symbols aren't really the way to go for this - and honestly I can't think of any other solution that would be clean, but if you guys come up with something, I'd be happy to implement it :grin:

**Comment by gaearon** [comment]
By the way, for an example of `Object.freeze` being used, see https://github.com/gcanti/redux-tcomb

**Comment by FredyC** [comment]
Alright, I wasn't fiddling with tcomb yet, in that case it's a valid point.
